# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emrah's Blog
email: emrah.kaya@deepnetwork.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing lessons learned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/emrahkaya" # the base hostname & protocol for your site
github_username:  emrahkaya

# Build settings
markdown: kramdown
